dist: trusty
sudo: required

language: python
python:
  - "3.6"

cache: pip

git:
  submodules: false

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

env:
  global:
    - CHROMEDRIVER_VERSION=2.29
    - DISPLAY=:99.0
  matrix:
    - TESTS=functional
    - TESTS=functional CHROME_WRAPPER_PATH=devtools/chrome-wrapper.sh DEVTOOLS_PROXY_PATH=dist/linux/devtools-proxy
    - TESTS=integration
    - TESTS=integration CHROME_WRAPPER_PATH=devtools/chrome-wrapper.sh DEVTOOLS_PROXY_PATH=dist/linux/devtools-proxy
    - TESTS=compatibility
    - TESTS=compatibility CHROME_WRAPPER_PATH=devtools/chrome-wrapper.sh DEVTOOLS_PROXY_PATH=dist/linux/devtools-proxy
    - TESTS=compatibility DTP_UJSON=true
    - TESTS=compatibility DTP_UVLOOP=true

matrix:
  fast_finish: true
  allow_failures:
    - env: TESTS=compatibility DTP_UJSON=true
    - env: TESTS=compatibility DTP_UVLOOP=true

before_install:
  - |
      if [[ ${TESTS} != "functional" ]]; then
        curl -L -O "http://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip"
        unzip -o chromedriver_linux64.zip -d /tmp/ && chmod +x /tmp/chromedriver && sudo mv /tmp/chromedriver /usr/local/bin/chromedriver
      fi

install:
  - pip install -Ur requirements-dev.txt

before_script:
  - if [[ ${DEVTOOLS_PROXY_PATH} == "dist/linux/devtools-proxy" ]]; then ./build-standalone.sh; fi
  - if [[ ${TESTS} == "compatibility" ]]; then git submodule update --init --recursive; fi
  - sh -e /etc/init.d/xvfb start

script:
  - ./run-tests.sh ${TESTS}

notifications:
  email: false
